#!/bin/bash
# Build script for Android APK with Rust FFI compilation

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$SCRIPT_DIR"
FLUTTER_APP="$WORKSPACE_ROOT/flutter_app"

echo "🦦 Otter Android Build Script"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Check prerequisites
check_prerequisites() {
    echo "📋 Checking prerequisites..."
    
    # Check Flutter
    if ! command -v flutter &> /dev/null; then
        echo "❌ Flutter not found. Install from https://flutter.dev/docs/get-started"
        exit 1
    fi
    echo "✅ Flutter: $(flutter --version | head -n1)"
    
    # Check Rust
    if ! command -v rustc &> /dev/null; then
        echo "❌ Rust not found. Install from https://rustup.rs"
        exit 1
    fi
    echo "✅ Rust: $(rustc --version)"
    
    # Check cargo ndk
    if ! cargo ndk --version &> /dev/null; then
        echo "⚠️  cargo-ndk not found. Installing..."
        cargo install cargo-ndk
    fi
    echo "✅ cargo-ndk: $(cargo ndk --version)"
    
    # Check Android targets
    echo "📦 Checking Rust Android targets..."
    for target in aarch64-linux-android armv7-linux-androideabi x86_64-linux-android; do
        if ! rustup target list | grep -q "^$target (installed)"; then
            echo "  Installing $target..."
            rustup target add "$target"
        fi
    done
    echo "✅ All Android targets installed"
}

# Configure Android SDK paths
configure_android() {
    echo ""
    echo "🔧 Configuring Android SDK..."
    
    if [ ! -f "$FLUTTER_APP/android/local.properties" ]; then
        echo "⚠️  local.properties not found. Creating from template..."
        
        # Try to detect Android SDK
        if [ -n "$ANDROID_SDK_ROOT" ]; then
            SDK_PATH="$ANDROID_SDK_ROOT"
        elif [ -n "$ANDROID_HOME" ]; then
            SDK_PATH="$ANDROID_HOME"
        elif [ -d "$HOME/Android/Sdk" ]; then
            SDK_PATH="$HOME/Android/Sdk"
        else
            echo "❌ Android SDK not found!"
            echo "   Set ANDROID_SDK_ROOT or ANDROID_HOME environment variable"
            echo "   Or install via Android Studio SDK Manager"
            exit 1
        fi
        
        cat > "$FLUTTER_APP/android/local.properties" << EOF
# Generated by build script
sdk.dir=$SDK_PATH
ndkVersion=25.2.9519653
EOF
        
        echo "✅ Generated local.properties"
        echo "   SDK: $SDK_PATH"
    else
        echo "✅ local.properties exists"
    fi
    
    # Verify NDK
    SDK_PATH=$(grep "sdk.dir" "$FLUTTER_APP/android/local.properties" | cut -d= -f2)
    NDK_PATH="$SDK_PATH/ndk/25.2.9519653"
    
    if [ ! -d "$NDK_PATH" ]; then
        echo ""
        echo "⚠️  NDK 25.2.9519653 not found at $NDK_PATH"
        echo "   Please install via Android Studio SDK Manager:"
        echo "   1. Tools > SDK Manager"
        echo "   2. SDK Tools > NDK (Side by side)"
        echo "   3. Ensure version 25.2.9519653 is installed"
        exit 1
    fi
    echo "✅ NDK found: $NDK_PATH"
}

# Build native Rust library
build_rust_ffi() {
    echo ""
    echo "🔨 Building Rust FFI library..."
    
    cd "$WORKSPACE_ROOT"
    
    # Create output directory
    OUTPUT_DIR="$FLUTTER_APP/android/app/src/main/jniLibs"
    mkdir -p "$OUTPUT_DIR"
    
    # Build for each architecture
    targets=(
        "aarch64-linux-android:arm64-v8a"
        "armv7-linux-androideabi:armeabi-v7a"
        "x86_64-linux-android:x86_64"
    )
    
    for target_spec in "${targets[@]}"; do
        rust_target="${target_spec%%:*}"
        abi_dir="${target_spec##*:}"
        
        echo ""
        echo "  📦 Building for $abi_dir ($rust_target)..."
        
        cargo ndk \
            --android-platform 21 \
            --output "$OUTPUT_DIR" \
            build -p otter-mobile \
            --lib \
            --target "$rust_target" \
            --release
        
        lib_path="$OUTPUT_DIR/$abi_dir/libotter_mobile.so"
        if [ -f "$lib_path" ]; then
            size=$(ls -lh "$lib_path" | awk '{print $5}')
            echo "  ✅ Built: $lib_path ($size)"
        else
            echo "  ❌ Failed to build for $rust_target"
            exit 1
        fi
    done
}

# Build Flutter app
build_flutter() {
    echo ""
    echo "🏗️  Building Flutter App..."
    
    cd "$FLUTTER_APP"
    
    # Clean previous build artifacts
    flutter clean
    flutter pub get
    
    # Build APK
    if [ "$BUILD_TYPE" = "release" ]; then
        echo "📦 Building release APK..."
        flutter build apk --release
        apk_path="build/app/outputs/apk/release/app-release.apk"
    else
        echo "📦 Building debug APK..."
        flutter build apk --debug
        apk_path="build/app/outputs/apk/debug/app-debug.apk"
    fi
    
    if [ -f "$apk_path" ]; then
        size=$(ls -lh "$apk_path" | awk '{print $5}')
        echo "✅ APK built: $apk_path ($size)"
    else
        echo "❌ APK build failed"
        exit 1
    fi
}

# Main flow
main() {
    BUILD_TYPE="${1:-debug}"
    
    if [ "$BUILD_TYPE" != "debug" ] && [ "$BUILD_TYPE" != "release" ]; then
        echo "Usage: $0 [debug|release]"
        exit 1
    fi
    
    check_prerequisites
    configure_android
    build_rust_ffi
    build_flutter
    
    echo ""
    echo "✨ Build complete!"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    
    if [ "$BUILD_TYPE" = "release" ]; then
        apk="$FLUTTER_APP/build/app/outputs/apk/release/app-release.apk"
    else
        apk="$FLUTTER_APP/build/app/outputs/apk/debug/app-debug.apk"
    fi
    
    echo "📱 APK ready: $apk"
    echo ""
    echo "To install on device:"
    echo "  adb install '$apk'"
    echo "Or:"
    echo "  flutter run"
}

main "$@"
